from enum import StrEnum

from pydantic import BaseModel


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_DURATION = "INVALID_DURATION"
    INVALID_RESOLUTION = "INVALID_RESOLUTION"
    QUEUE_FULL = "QUEUE_FULL"
    SERVER_STOPPING = "SERVER_STOPPING"
    GENERATION_NOT_FOUND = "GENERATION_NOT_FOUND"
    OUTPUT_NOT_READY = "OUTPUT_NOT_READY"
    OUTPUT_EXPIRED = "OUTPUT_EXPIRED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_EXPIRED = "ASSET_EXPIRED"
    ASSET_IN_USE = "ASSET_IN_USE"
    UPLOAD_TOO_LARGE = "UPLOAD_TOO_LARGE"
    INVALID_MEDIA = "INVALID_MEDIA"
    MEDIA_UNAVAILABLE = "MEDIA_UNAVAILABLE"
    UNSUPPORTED_PIPELINE = "UNSUPPORTED_PIPELINE"
    INFERENCE_UNAVAILABLE = "INFERENCE_UNAVAILABLE"
    UPSTREAM_INCOMPATIBLE = "UPSTREAM_INCOMPATIBLE"
    CUDA_UNAVAILABLE = "CUDA_UNAVAILABLE"
    CUDA_OUT_OF_MEMORY = "CUDA_OUT_OF_MEMORY"
    MODEL_NOT_INSTALLED = "MODEL_NOT_INSTALLED"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    OUTPUT_ENCODING_FAILED = "OUTPUT_ENCODING_FAILED"
    OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"
    GENERATION_FAILED = "GENERATION_FAILED"
    GENERATION_CANCELLED = "GENERATION_CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    NOT_FOUND = "NOT_FOUND"


class ErrorDetail(BaseModel):
    code: ErrorCode
    message: str


class ErrorResponse(BaseModel):
    error: ErrorDetail


class ServiceError(Exception):
    def __init__(self, code: ErrorCode, message: str, status: int = 400) -> None:
        super().__init__(message)
        self.detail = ErrorDetail(code=code, message=message)
        self.status = status
